ci: pre-commit hook for Rust

diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -1,28 +1,78 @@
 #!/bin/bash
 
-if [ ! -e "./gradlew" ]; then
-  exit 0
+echo "[pre-commit check]"
+
+if ! [ -x "$(command -v cargo)" ]; then
+  echo -e 'Rust toolchains are not installed!'
+  echo
+  echo 'If you are running on Unix-like platform, you can follow the on-screen instructions:'
+  echo
+  echo "  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
+  echo
+  echo 'If you are running on Windows, or you want to install'
+  echo 'Rust toolchains via package managers, you can see:'
+  echo
+  echo '- [Install Rust - rust-lang.org](https://www.rust-lang.org/tools/install)'
+  echo '- [Other Rust Installation Methods](https://forge.rust-lang.org/infra/other-installation-methods.html)'
+  exit 1
 fi
 
-CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $NF ~ /\.kts?$/ { print $NF }')"
+kotlin() {
+  if [ ! -e "./gradlew" ]; then
+    return 0
+  fi
 
-if [ -z "$CHANGED_FILES" ]; then
-  echo "No Kotlin staged files."
-  exit 0
+  CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $NF ~ /\.kts?$/ { print $NF }')"
+
+  if [ -z "$CHANGED_FILES" ]; then
+    echo "No Kotlin staged files."
+    return 0
+  fi
+
+  echo '[pre-commit] Executing Gradle spotlessCheck before commit'
+
+  git stash --quiet --keep-index
+
+  ./gradlew spotlessCheck --daemon
+
+  RESULT=$?
+
+  git stash pop -q
+
+  if [ "$RESULT" -ne "0" ]; then
+    echo -e "spotlessCheck failed..."
+    echo -e 'You can try "./gradlew spotlessApply" to apply auto-fixes.'
+  fi
+
+  return $RESULT
+}
+
+rust() {
+  cd sorapointa-native || return 0
+
+  CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $NF ~ /\.rs$/ { print $NF }')"
+
+  if [ -z "$CHANGED_FILES" ]; then
+    echo "No Rust staged files."
+    return 0
+  fi
+
+  if ! cargo clippy -- -D warnings; then
+    echo -e "cargo clippy failed..."
+    return 1
+  fi
+
+  if ! cargo fmt --all -- --check; then
+    echo -e "cargo fmt failed..."
+    echo -e "You can manually run 'cargo fmt' at './sorapointa-native' for auto format"
+    return 1
+  fi
+}
+
+if ! kotlin; then
+  exit 1
 fi
 
-echo '[pre-commit] Executing Gradle spotlessCheck before commit'
-
-git stash --quiet --keep-index
-
-./gradlew spotlessCheck --daemon
-
-RESULT=$?
-
-git stash pop -q
-
-if [ "$RESULT" -ne "0" ]; then
-  echo -e "spotlessCheck failed..."
-  echo -e 'You can try "./gradlew spotlessApply" to apply auto-fixes.'
-  exit $RESULT
+if ! rust; then
+  exit 1
 fi
