build: `spotless` for faster format check

diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -1,40 +1,28 @@
-#!/bin/sh
-######## KTLINT-GRADLE HOOK START ########
+#!/bin/bash
 
-echo "======== KTLINT ========"
+if [ ! -e "./gradlew" ]; then
+  exit 0
+fi
 
 CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $NF ~ /\.kts?$/ { print $NF }')"
 
 if [ -z "$CHANGED_FILES" ]; then
-    echo "No Kotlin staged files."
-    exit 0
-fi;
-
-echo "Running ktlint over these files:"
-echo "$CHANGED_FILES"
-
-diff=.git/unstaged-ktlint-git-hook.diff
-git diff --color=never > $diff
-if [ -s $diff ]; then
-  git apply -R $diff
+  echo "No Kotlin staged files."
+  exit 0
 fi
 
-./gradlew --quiet ktlintFormat -PinternalKtlintGitFilter="$CHANGED_FILES"
-gradle_command_exit_code=$?
+echo '[pre-commit] Executing Gradle spotlessCheck before commit'
 
-echo "$CHANGED_FILES" | while read -r file; do
-    if [ -f $file ]; then
-        git add $file
-    fi
-done
+git stash --quiet --keep-index
 
+./gradlew spotlessCheck --daemon
 
-if [ -s $diff ]; then
-  git apply --ignore-whitespace $diff
+RESULT=$?
+
+git stash pop -q
+
+if [ "$RESULT" -ne "0" ]; then
+  echo -e "spotlessCheck failed..."
+  echo -e 'You can try "./gradlew spotlessApply" to apply auto-fixes.'
+  exit $RESULT
 fi
-rm $diff
-unset diff
-
-echo
-exit $gradle_command_exit_code
-######## KTLINT-GRADLE HOOK END ########
